export const FETCH_PROPERTIES = 'FETCH_PROPERTIES';
export const RECEIVE_PROPERTIES = 'RECEIVE_PROPERTIES';

export const FETCH_PROPERTY_HISTORY = 'FETCH_PROPERTY_HISTORY';
export const RECEIVE_PROPERTY_HISTORY = 'RECEIVE_PROPERTY_HISTORY';

export const DELETE_PROPERTY_EXECUTED = 'DELETE_PROPERTY_EXECUTED';
